/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as PiliticaPrivacidadRouteImport } from './routes/pilitica-privacidad'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticulosIndexRouteImport } from './routes/articulos.index'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ArticulosSlugRouteImport } from './routes/articulos.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PiliticaPrivacidadRoute = PiliticaPrivacidadRouteImport.update({
  id: '/pilitica-privacidad',
  path: '/pilitica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/articulos/',
  path: '/articulos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosSlugRoute = ArticulosSlugRouteImport.update({
  id: '/articulos/$slug',
  path: '/articulos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/buscar': typeof BuscarRoute
  '/contacto': typeof ContactoRoute
  '/pilitica-privacidad': typeof PiliticaPrivacidadRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/buscar': typeof BuscarRoute
  '/contacto': typeof ContactoRoute
  '/pilitica-privacidad': typeof PiliticaPrivacidadRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/articulos': typeof ArticulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/buscar': typeof BuscarRoute
  '/contacto': typeof ContactoRoute
  '/pilitica-privacidad': typeof PiliticaPrivacidadRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/buscar'
    | '/contacto'
    | '/pilitica-privacidad'
    | '/politica-cookies'
    | '/sitemap.xml'
    | '/sobre'
    | '/articulos/$slug'
    | '/categoria/$slug'
    | '/articulos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/buscar'
    | '/contacto'
    | '/pilitica-privacidad'
    | '/politica-cookies'
    | '/sitemap.xml'
    | '/sobre'
    | '/articulos/$slug'
    | '/categoria/$slug'
    | '/articulos'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/buscar'
    | '/contacto'
    | '/pilitica-privacidad'
    | '/politica-cookies'
    | '/sitemap.xml'
    | '/sobre'
    | '/articulos/$slug'
    | '/categoria/$slug'
    | '/articulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BuscarRoute: typeof BuscarRoute
  ContactoRoute: typeof ContactoRoute
  PiliticaPrivacidadRoute: typeof PiliticaPrivacidadRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ArticulosSlugRoute: typeof ArticulosSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilitica-privacidad': {
      id: '/pilitica-privacidad'
      path: '/pilitica-privacidad'
      fullPath: '/pilitica-privacidad'
      preLoaderRoute: typeof PiliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/articulos'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/$slug': {
      id: '/articulos/$slug'
      path: '/articulos/$slug'
      fullPath: '/articulos/$slug'
      preLoaderRoute: typeof ArticulosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BuscarRoute: BuscarRoute,
  ContactoRoute: ContactoRoute,
  PiliticaPrivacidadRoute: PiliticaPrivacidadRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ArticulosSlugRoute: ArticulosSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
